import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono, Inter } from "next/font/google";
import { AppSidebar, SideBarSelectionProvider } from "@/components/app-sidebar";
import { DynamicBreadcrumb } from "@/components/dynamic-breadcrumb";
import { Separator } from "@/components/ui/separator";
import LayoutWrapper from '../components/layout/LayoutWrapper';
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar/sidebar";
import { UserProvider } from "@/context/userContext";


// Roboto for sans-serif (default UI text)
const interSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
  display: "swap",
  weight: ["400", "700"], // add weights you want
});

// JetBrains Mono for monospace (code blocks, etc)
const interMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-inter-mono",
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interSans.variable} ${interMono.variable}`}>
      <body className={`font-sans antialiased`}>
        <UserProvider>
          <SidebarProvider>
            <SideBarSelectionProvider>
              <LayoutWrapper>{children}</LayoutWrapper>
            </SideBarSelectionProvider>
          </SidebarProvider>
        </UserProvider>
      </body>
    </html>
  );
}
