version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - go-service
    environment:
      - REACT_APP_GO_API=http://localhost:8081
    volumes:
      - ./frontend:/app

  upload-service:
    build: ./services/upload-service
    ports:
      - "8081:8081"
    volumes:
      - ./images:/app/images
    environment:
      - IMAGE_PATH=/app/images


  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: journal
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    ports:
      -"5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  images:
