version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - go-service
      - java-service
    environment:
      - REACT_APP_GO_API=http://localhost:8081
      - REACT_APP_JAVA_API=http://localhost:8080
    volumes:
      - ./frontend:/app

  go-service:
    build: ./go-service
    ports:
      - "8081:8081"
    volumes:
      - ./images:/app/images
    environment:
      - IMAGE_PATH=/app/images

  java-service:
    build: ./java-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/journal
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=secret

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: journal
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  images:
